name: Build and upload documentation

on:
  release:
    types: [published]
  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
  
  
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v3
    - name:  build
      working-directory: docs
      run:   make clean html
    - name: ftp-clean
      # You may pin to the exact commit or the version.
      # uses: taylorgibb/ftp-clean@37c34052bd2170bcab847bf8b61df5f4ff526093
      uses: taylorgibb/ftp-clean@v2.0.3
      with:
        # FTP host
        host: ${{ secrets.WEB_FTP_SERVER }}
        # FTP user
        user:  ${{ secrets.WEB_FTP_USERNAME }}
        # FTP password
        password: ${{ secrets.WEB_FTP_PASSWORD }}
        # Files and directories which should be excluded from being removed.
        exclude: "stats"

    - name: FTP Deploy
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@d0aa83872616587eb552bc831bb9166b3f9c5ad5
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        # ftp server
        server: ${{ secrets.WEB_FTP_SERVER }}
        # ftp username
        username: ${{ secrets.WEB_FTP_USERNAME }}
        # ftp password
        password: ${{ secrets.WEB_FTP_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
    
  
